name: Sync and Republish Docker Images

on:
  push:
    branches:
      - dev-registry

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  sync-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image:
          - name: hadoop
            source: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/hadoop:latest
          - name: spark-worker
            source: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/spark-worker:latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull source image
        run: |
          echo "Pulling ${{ matrix.image.source }}"
          docker pull ${{ matrix.image.source }}

      - name: Tag and push image
        run: |
          SOURCE_IMAGE="${{ matrix.image.source }}"
          TARGET_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ matrix.image.name }}"
          
          # Tag con latest
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}:latest
          docker push ${TARGET_IMAGE}:latest
          
          # Tag con timestamp per versioning
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}:${TIMESTAMP}
          docker push ${TARGET_IMAGE}:${TIMESTAMP}
          
          echo "✅ Successfully pushed ${TARGET_IMAGE}:latest and ${TARGET_IMAGE}:${TIMESTAMP}"

      - name: Clean up local images
        if: always()
        run: |
          docker rmi ${{ matrix.image.source }} || true
          docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ matrix.image.name }}:latest || true