name: Build and publish Spark and Hadoop images

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io

jobs:
  build-spark-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Spark Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./spark
          file: ./spark/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/spark-worker:latest
            ${{ env.REGISTRY }}/spark-worker:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

  build-hadoop-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Hadoop image
        uses: docker/build-push-action@v5
        with:
          context: ./hadoop_image
          file: ./hadoop_image/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/hadoop:latest
            ${{ env.REGISTRY }}/hadoop:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}